name: CI

on:
  push:
  pull_request_target:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Update environment
        run: uv sync --all-extras --dev

      - name: Lint
        run: uv run ruff check

      - name: Format
        run: uv run ruff format --check

      - name: Run tests
        run: uv run pytest --cov-report=xml --junitxml=junit.xml -o junit_family=legacy

      - uses: codecov/test-results-action@v1
        if: ${{ !cancelled() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}