[browser]
# Disable sending usage statistics to Streamlit.
gatherUsageStats = false

[client]
# Show only options set externally (e.g. hrough st.set_page_config)
toolbarMode = "minimal"

[logger]
# Info is a default logging level, but keep for reference
level = "info"

# Add logging level and logger name to make logs more complete
messageFormat = "%(asctime)s %(levelname) -7s %(name)s: %(message)s"

[runner]
# Raise an exception after adding unserializable data to Session State.
enforceSerializableSessionState = true

[server]
# Don't open a new browser tab on every app run, it's annoying.
headless = true

# Enforce port, if not defined Streamlit will pick 8501, than 8502, etc.
# Stable port is crucial for authentication redirection configuration, see .env file.
port = 8501

# Automatically rerun script when the file is modified on disk.
runOnSave = true

[theme]
# Force light theme to make application logo visible and avoid headache with all other components.
base = "light"
